dist: trusty
sudo: required
language: php
php:
  - 5.6
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE cchits_ci DEFAULT CHARACTER SET 'utf8' DEFAULT COLLATE 'utf8_general_ci'"
  - mysql -e "CREATE USER 'cchits_ci'@'localhost' IDENTIFIED BY 'cchits_ci'"
  - mysql -e "GRANT ALL PRIVILEGES ON cchits_ci.* TO 'cchits_ci'@'localhost'"
  - mysql -e "USE cchits_ci; SOURCE ci/sql/cchits.sql;"
before_script:
  - cp ci/conf/CI_CONFIG.php CONFIG/LOCAL_CONFIG.php
script:
  - php ci/phpcs/phpcs.phar --standard=ci/phpcs CLASSES/
  - phpunit --configuration ci/conf/travis.xml --bootstrap CLASSES/autoloader.php TESTS/
